# -*- coding: utf-8 -*-
"""1. RAG-Getting Started

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wswt7-A3uRis6J2susLK-O28VCpUTk93
"""

!uv init

!uv add -r requirements.txt

# Fix opentelemetry dependency for chromadb
# Uninstall potentially conflicting opentelemetry packages
!pip uninstall -y opentelemetry-api opentelemetry-sdk

# Install required libraries, allowing chromadb to manage its opentelemetry dependencies
!pip install sentence-transformers
!pip install chromadb
!pip install faiss-cpu

!pip install langchain_community
!pip install langchain
!pip install langchain_core
!pip install langchain_text_splitters

from langchain_core.documents import Document

doc= Document(
    page_content = "This is a text file. Foe demonstrate \"Document\" class inside Langchain",
    metadata={
        "source":"https:/examples.com/example.txt",
        "author":"John Doe",
        "date":"2023-01-01",
        "page_count":1
    }
    )

doc

import os
os.makedirs("/content/data/text_files/",exist_ok=True)

"""### TextLoader"""



loader= TextLoader("/content/data/text_files/Future Improvements to the Agricult.txt",encoding="utf-8")
document= loader.load()
print(document)

"""#Directory Loader

##Text directory loader
"""

from langchain_community.document_loaders import DirectoryLoader

dir_load= DirectoryLoader(
    "/content/data/text_files/",
    glob="**/*.txt",
    show_progress=True,
    use_multithreading=True,
    loader_cls=TextLoader,
    loader_kwargs={"encoding":"utf-8"}
)

txt_files=dir_load.load()

txt_files

"""##PDF Directory Loader"""

#!uv add pymupdf
!pip install pymupdf

os.makedirs("/content/data/pdf_files",exist_ok=True)

from langchain_community.document_loaders import PyMuPDFLoader

pdf_dir_load= DirectoryLoader(
    "/content/data/pdf_files/",
    glob="**/*.pdf",
    show_progress=True,
    use_multithreading=True,
    loader_cls=PyMuPDFLoader
)

pdf_files=pdf_dir_load.load()

pdf_files

"""# Chunking"""

!uv add langchain-text-splitters

import langchain
import langchain_core
from langchain_community.document_loaders import TextLoader
from langchain_community.document_loaders import DirectoryLoader
from langchain_community.document_loaders import PyMuPDFLoader
from langchain_text_splitters import RecursiveCharacterTextSplitter
import os
from pathlib import Path
os.makedirs("/content/data/pdf_files",exist_ok=True)

def process_all_pdfs(pdf_dir):
  """ Process all pdf files in a directory """
  all_documents=[]

  pdf_files=list(Path(pdf_dir).glob("**/*.pdf"))
  print(f"found {len(pdf_files)} pdf files inside directory")


  for pdf_file in pdf_files:
    print(f"Processing {pdf_file}")
    try:
        loader=PyMuPDFLoader(str(pdf_file))
        documents=loader.load()
        # add Source info to meta data
        for doc in documents:
          doc.metadata["source"]=str(pdf_file)
          doc.metadata["page"]=str(doc.metadata["page"])
          doc.metadata["file_type"]= "pdf"

        all_documents.extend(documents)
        print(f"loaded {len(documents)} pages")
    except Exception as e:
      print(f"Error processing {pdf_file}: {e}")
  print(f"Total documents: {len(all_documents)}")
  return all_documents

all_pdf_document= process_all_pdfs("/content/data/pdf_files")

all_pdf_document

## Text splitiing and chuking

def split_documents(documents,chunk_size=500,chunk_overlap=100):
  """ Slipt document into smaller chunks for better RAG performance"""
  print("="*50,"Chunking START","="*50)
  text_splitter= RecursiveCharacterTextSplitter(
      chunk_size=chunk_size,
      chunk_overlap=chunk_overlap,
      length_function=len,
      separators=["\n\n", "\n"," ", ""]
  )
  split_documents= text_splitter.split_documents(documents)
  print(f"Original document: {len(documents)}, Slipt into {len(split_documents)} chunks")

  if split_documents:
    print(f"Example chunk: {split_documents[0].page_content}")

  print("="*50,"Chunking Done","="*50)
  return split_documents

chunk_docs= split_documents(all_pdf_document)

chunk_docs

"""Chunking Done

# Vector Storage

#embeding and Vector store
"""

!pip install -U sentence-transformers

from sentence_transformers import SentenceTransformer
sentences = ["This is an example sentence", "Each sentence is converted"]

model = SentenceTransformer('sentence-transformers/all-MiniLM-L6-v2')
embeddings = model.encode(sentences)
print(embeddings)

import numpy as np
from typing import List, Tuple, Dict, Any
import uuid
from sklearn.metrics.pairwise import cosine_similarity
from chromadb.config import Settings
import chromadb
from langchain_community.document_loaders import TextLoader
import os

class embeddingManager:
  """Handels document embedding generation using SentenceTransformer """
  def __init__(self,model_name:str="all-MiniLM-L6-v2"):
    """
    Intializer for embedingg manager

    Args:
      model_name (str): SentenceTransformer model name, Hugging face model name for sentence embeding
    """
    self.model_name= model_name
    self.model= None
    self._load_model()
  def _load_model(self):
    """ Load SentenceTransformer model """
    try:
      from sentence_transformers import SentenceTransformer
      self.model= SentenceTransformer(self.model_name)
      print(f"Model load successfully, embedding diamension is {self.model.get_sentence_embedding_dimension()}")
    except Exception as e:
      print(f"Error loading model {self.model_name}: {e}")
      raise
  def generate_embedding(self,texts:List[str]) -> np.ndarray:
    """
    generate embedding for a list of texts.

    Args:
       texts: List of string to embed
    returns:
       numpy array of embedding with shape (len(texts), embedding_dim)
    """
    if not self.model:
      raise ValueError("Model not loaded")
    print(f"Generating embbeding for {len(texts)} texts....")
    embeddings= self.model.encode(texts,show_progress_bar=True)
    print(f"generated embeding for shape{embeddings.shape}")
    return embeddings

## Intialize the embeding manager
embeding_manager= embeddingManager()
embeding_manager

"""#Vectore Store"""

class Vector_Store:
  """
  Manages documents vector store using ChromaDB
  """

  def __init__(self,collection_name:str="pdf_documents", persist_dir:str='/content/data/pdf_vectore'):
    """
    Intializer of the vectore store
    Args:
      collection_name:name of the ChromaDB collection
      persist_dir:Directory to keep the vectore store data
    """
    self.collection_name= collection_name
    self.persist_dir= persist_dir
    self.client= None
    self.collection= None
    self._initilize_store()

  def _initilize_store(self):
    """ Initialize the vectore store """
    try:
        os.makedirs(self.persist_dir,exist_ok=True)
        self.client= chromadb.PersistentClient(path=self.persist_dir)

        #Get or create collection
        self.collection=self.client.get_or_create_collection(
            name=self.collection_name,
            metadata={"description": "Pdf data embedding vector for RAG"}

        )

        print(f"vectore store initilized successfully")
        print(f"Collection name: {self.collection.name}")
        print(f"Collection metadata: {self.collection.metadata}")
        print(f"Collection Count:{self.collection.count()}")
    except Exception as e:
      print(f"Error initilizing vectore store: {e}")
      raise

  def add_document(self, documents:List[Any],embbedings:np.ndarray):
    """
    Add documents to the vectore store
    Args:
      documents: List of documents to add to the vectore store
      embedding: Coresponding embeding for the documents

    """
    print(f"DEBUG: Length of documents received: {len(documents)}")
    print(f"DEBUG: Length of embeddings received: {len(embbedings)}")
    if len(documents) != len(embbedings):
      raise ValueError("Number of documents and embeddings must be equal")


    print(f"Adding {len(documents)} documents to the vectore store")


    ids=[]
    metadatas=[]
    documents_texts=[]
    embeding_list=[]
    for i,(doc,embedding) in enumerate(zip(documents,embbedings)):
      docid= f"doc_{uuid.uuid4().hex[:8]}_{i}"
      ids.append(docid)
      metadata = dict(doc.metadata)
      metadata["doc_index"]=i
      metadata["content_length"]=len(doc.page_content)
      metadatas.append(metadata)
      documents_texts.append(doc.page_content)
      embeding_list.append(embedding.tolist())

    print(f"Adding {len(documents)} documents to the vectore store")

    try:
      self.collection.add(
          ids=ids,
          documents=documents_texts,
          metadatas=metadatas,
          embeddings=embeding_list
      )
      print(f"Added {len(documents)} documents to the vectore store")

      print(f"Collection Count: {self.collection.count()}")
    except Exception as e:
        print(f"Error adding documents to the vectore store: {e}")
        raise

vector_store= Vector_Store()
vector_store

## Convert chunk text to embeding

texts= [doc.page_content for doc in chunk_docs]

## generate embedings
embeding_texts= embeding_manager.generate_embedding(texts)

# store it in chromadb
vector_store.add_document(chunk_docs,embeding_texts)

"""#Full Data Pipeline : PDF -> Chunks-> Embeding -> vectorDB(ChromaDB)"""

# Fix opentelemetry dependency for chromadb
# Uninstall potentially conflicting opentelemetry packages
!pip uninstall -y opentelemetry-api opentelemetry-sdk

# Install required libraries, allowing chromadb to manage its opentelemetry dependencies
!pip install sentence-transformers
!pip install chromadb
!pip install faiss-cpu

!pip install langchain_community
!pip install langchain
!pip install langchain_core
!pip install langchain_text_splitters


!pip install pymupdf

"""## 0. Load Pdf files"""

from langchain_community.document_loaders import PyMuPDFLoader

pdf_dir_load= DirectoryLoader(
    "/content/data/pdf_files/",
    glob="**/*.pdf",
    show_progress=True,
    use_multithreading=True,
    loader_cls=PyMuPDFLoader
)

pdf_files=pdf_dir_load.load()

pdf_files

"""##1. Process PDF Files

"""

def process_all_pdfs(pdf_dir):
  """ Process all pdf files in a directory """
  all_documents=[]

  pdf_files=list(Path(pdf_dir).glob("**/*.pdf"))
  print(f"found {len(pdf_files)} pdf files inside directory")


  for pdf_file in pdf_files:
    print(f"Processing {pdf_file}")
    try:
        loader=PyMuPDFLoader(str(pdf_file))
        documents=loader.load()
        # add Source info to meta data
        for doc in documents:
          doc.metadata["source"]=str(pdf_file)
          doc.metadata["page"]=str(doc.metadata["page"])
          doc.metadata["file_type"]= "pdf"

        all_documents.extend(documents)
        print(f"loaded {len(documents)} pages")
    except Exception as e:
      print(f"Error processing {pdf_file}: {e}")
  print(f"Total documents: {len(all_documents)}")
  return all_documents

"""##2. Chunking"""

## Text splitiing and chuking

def split_documents(documents,chunk_size=500,chunk_overlap=100):
  """ Slipt document into smaller chunks for better RAG performance"""
  print("="*50,"Chunking START","="*50)
  text_splitter= RecursiveCharacterTextSplitter(
      chunk_size=chunk_size,
      chunk_overlap=chunk_overlap,
      length_function=len,
      separators=["\n\n", "\n"," ", ""]
  )
  split_documents= text_splitter.split_documents(documents)
  print(f"Original document: {len(documents)}, Slipt into {len(split_documents)} chunks")

  if split_documents:
    print(f"Example chunk: {split_documents[0].page_content}")

  print("="*50,"Chunking Done","="*50)
  return split_documents

"""## 3. Embeding Manager Class"""

import numpy as np
from typing import List, Tuple, Dict, Any
import uuid
from sklearn.metrics.pairwise import cosine_similarity
from chromadb.config import Settings
import chromadb
from langchain_community.document_loaders import TextLoader
import os

class embeddingManager:
  """Handels document embedding generation using SentenceTransformer """
  def __init__(self,model_name:str="all-MiniLM-L6-v2"):
    """
    Intializer for embedingg manager

    Args:
      model_name (str): SentenceTransformer model name, Hugging face model name for sentence embeding
    """
    self.model_name= model_name
    self.model= None
    self._load_model()
  def _load_model(self):
    """ Load SentenceTransformer model """
    try:
      from sentence_transformers import SentenceTransformer
      self.model= SentenceTransformer(self.model_name)
      print(f"Model load successfully, embedding diamension is {self.model.get_sentence_embedding_dimension()}")
    except Exception as e:
      print(f"Error loading model {self.model_name}: {e}")
      raise
  def generate_embedding(self,texts:List[str]) -> np.ndarray:
    """
    generate embedding for a list of texts.

    Args:
       texts: List of string to embed
    returns:
       numpy array of embedding with shape (len(texts), embedding_dim)
    """
    if not self.model:
      raise ValueError("Model not loaded")
    print(f"Generating embbeding for {len(texts)} texts....")
    embeddings= self.model.encode(texts,show_progress_bar=True)
    print(f"generated embeding for shape{embeddings.shape}")
    return embeddings

"""##4. Vector store class"""

class Vector_Store:
  """
  Manages documents vector store using ChromaDB
  """

  def __init__(self,collection_name:str="pdf_documents", persist_dir:str='/content/data/pdf_vectore'):
    """
    Intializer of the vectore store
    Args:
      collection_name:name of the ChromaDB collection
      persist_dir:Directory to keep the vectore store data
    """
    self.collection_name= collection_name
    self.persist_dir= persist_dir
    self.client= None
    self.collection= None
    self._initilize_store()

  def _initilize_store(self):
    """ Initialize the vectore store """
    try:
        os.makedirs(self.persist_dir,exist_ok=True)
        self.client= chromadb.PersistentClient(path=self.persist_dir)

        #Get or create collection
        self.collection=self.client.get_or_create_collection(
            name=self.collection_name,
            metadata={"description": "Pdf data embedding vector for RAG"}

        )

        print(f"vectore store initilized successfully")
        print(f"Collection name: {self.collection.name}")
        print(f"Collection metadata: {self.collection.metadata}")
        print(f"Collection Count:{self.collection.count()}")
    except Exception as e:
      print(f"Error initilizing vectore store: {e}")
      raise

  def add_document(self, documents:List[Any],embbedings:np.ndarray):
    """
    Add documents to the vectore store
    Args:
      documents: List of documents to add to the vectore store
      embedding: Coresponding embeding for the documents

    """
    print(f"DEBUG: Length of documents received: {len(documents)}")
    print(f"DEBUG: Length of embeddings received: {len(embbedings)}")
    if len(documents) != len(embbedings):
      raise ValueError("Number of documents and embeddings must be equal")


    print(f"Adding {len(documents)} documents to the vectore store")


    ids=[]
    metadatas=[]
    documents_texts=[]
    embeding_list=[]
    for i,(doc,embedding) in enumerate(zip(documents,embbedings)):
      docid= f"doc_{uuid.uuid4().hex[:8]}_{i}"
      ids.append(docid)
      metadata = dict(doc.metadata)
      metadata["doc_index"]=i
      metadata["content_length"]=len(doc.page_content)
      metadatas.append(metadata)
      documents_texts.append(doc.page_content)
      embeding_list.append(embedding.tolist())

    print(f"Adding {len(documents)} documents to the vectore store")

    try:
      self.collection.add(
          ids=ids,
          documents=documents_texts,
          metadatas=metadatas,
          embeddings=embeding_list
      )
      print(f"Added {len(documents)} documents to the vectore store")

      print(f"Collection Count: {self.collection.count()}")
    except Exception as e:
        print(f"Error adding documents to the vectore store: {e}")
        raise

"""## 5. Integration"""

#Load Pdf files
all_pdf_document= process_all_pdfs("/content/data/pdf_files")

#chunk Pdf files
chunk_docs= split_documents(all_pdf_document)

#convert chunk to text
texts= [doc.page_content for doc in chunk_docs]

# embedding the chunk texts
embeding_manager= embeddingManager()
embeding_texts= embeding_manager.generate_embedding(texts)

# store in a vectore database
vector_store= Vector_Store()
vector_store.add_document(chunk_docs,embeding_texts)

"""##6. RAG- Retriver


*  Search about specific topic in our vector store.


"""

class RAG_Retriver:
  """
  Handel query based retrival from out vector store
  """
  def __init__(self,vector_store:Vector_Store, embeding_manager:embeddingManager):
    """
    Intializer for RAG retriver
    Args:
      vectore_stopre: Vector_Store object
      embeding_manager: embeddingManager object


    """


    self.vector_store= vector_store
    self.embeding_manager= embeding_manager

  def retriver(self,query:str,top_k:int=5,score_threshold:float=0.0):
    """
    Retrieve relevant document for a query
    Args:
      query: query string to search for
      top_k: number of documents to return
      score_threshold: minimum score to return
    Returns:
      List of dictionary with document metadata and score
    """
    print(f"Retriving documents for query: {query}")
    print(f"Top k: {top_k}, Score threshold: {score_threshold}")

    query_embeding= self.embeding_manager.generate_embedding([query])[0]
    try:

      results= self.vector_store.collection.query(
          query_embeddings= [query_embeding.tolist()],
          n_results= top_k
      )

      retrived_docs=[]
      if results['documents'] and results['documents'][0]:
        documents= results['documents'][0]
        distances= results['distances'][0]
        metadata= results['metadatas'][0]
        ids= results['ids'][0]
        for i,(doc_id,document,distance,metadata) in enumerate(zip(ids,documents,distances,metadata)):
          similarity_score= 1- distance
          if similarity_score > score_threshold:
            retrived_docs.append({
                "id": doc_id,
                "content": document,
                "metadata": metadata,
                "score": similarity_score,
                "distance": distance,
                "rank":i+1
            })
            print(f"Retrived Document:{len(retrived_docs)}")
          else:
            print(f"No documents found with score above threshold {score_threshold}")

        return retrived_docs

    except Exception as e:
        print(f"Error retriving documents: {e}")
        return []

rag_retriver= RAG_Retriver(vector_store,embeding_manager)

rag_retriver.retriver("Practical Implications for Agriculture")

"""## Integration with groq LLM"""

!pip install langchain_groq

from google.colab import userdata
groq_api_key= userdata.get('groq_api_key')

import os
from langchain_groq import ChatGroq

model=ChatGroq(groq_api_key=groq_api_key,model_name='llama-3.1-8b-instant',temperature=0.1, max_tokens=1024)

def simple_rag(query,retriver,llm,top_k=3):
  results= retriver.retriver(query,top_k=top_k)
  context="\n\n".join([doc['content'] for  doc in results]) if results else ""
  if not context:
    return "No documents found"
  prompt= f""" use the follwing context to anser the user questions concisely, merge every thing and give a summaerized answer of the asked question
      Context: {context}

      Questions:{query}
      Answer:
  """
  response= llm.invoke([prompt.format(context=context,query=query)])
  return response.content

answer = simple_rag("Cambodia vs India coverage of Sentinal-2",rag_retriver,model,top_k=3)
print(answer)